### ISSUE TITLE
Серийный номер устройства

### ISSUE THREAD

**Issue by buzlachok** [blutz1982/go-nsexporter-libreview#1]
Добрый день.
Подгрузил данные в пустой кабинет. В файле настройки uniqueIdentifier: пустое оставил. 
Все отлично загрузилось т.е. я так понял сам ID устройства сгенерировался.
И в кабинете в моих устройствах номер не  появился, хотя все загружается.
Как правильно действовать, чтобы номер появился?
Спасибо.

**Comment by buzlachok** [comment]
![Снимок экрана от 2024-02-15 11-55-25](https://github.com/blutz1982/go-nsexporter-libreview/assets/74839758/431e592a-f019-4dec-846b-6b8b39962e20)

**Comment by blutz1982** [comment]
По всей видимости API libreview не валидирует пустой SN, считая его допустимым. Т.е. вероятно ваш серийный номер - это пустая строка.
 
Вообще кейс использования такой, что вы сначала через приложение librelink, хотя-бы раз сканируете сенсор и ваш сгенерированный идентификатор попадает на портал libreview. Далее его и нужно использовать.
